import "./globals.css";
import type { Metadata } from "next";
import Link from "next/link";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Planorario",
  description: "Generated by create next app",
};

import Box from "@mui/material/Box";
import TextField from "@mui/material/TextField";
import Container from "@mui/material/Container";
import Grid from "@mui/material/Grid";
import Item from "@mui/material/Grid";
import Typography from "@mui/material/Typography";
import BottomNavigation from "@mui/material/BottomNavigation";
import BottomNavigationAction from "@mui/material/BottomNavigationAction";

// icons
import MenuIcon from "@mui/icons-material/Menu";
import { CalendarMonth, Home } from "@mui/icons-material";

import ThemeRegistry from "../components/ThemeRegistry";
import CurrentlyTracking from "../components/CurrentlyTracking";
import ProfileNavButton from "../components/ProfileNavButton";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="dark" className="h-full">
      <body className="h-full">
        <ThemeRegistry options={{ key: "mui", prepend: false }}>
          <main className="h-full">
            <Box
              className="h-full flex"
              sx={{
                flexDirection: { xs: "column", md: "row-reverse" },
              }}
            >
              <Container
                maxWidth={false}
                className="grow"
                style={{ width: "calc(100% - 16px)" }}
              >
                {/* Logo Panel */}
                <Grid container spacing={2} className="h-28">
                  <Grid
                    item
                    xs={0}
                    md={3}
                    sx={{ display: { md: "block", xs: "none" } }}
                  >
                    <Item className="w-full h-full py-4 flex items-center">
                      <Typography variant="h4">
                        <Link href={"/"}>planorario</Link>
                      </Typography>
                    </Item>
                  </Grid>

                  {/* Currently tracking / Suggestion Panel */}
                  <Grid item xs={11} md={6}>
                    <Item className="h-full py-4 flex items-center">
                      <CurrentlyTracking></CurrentlyTracking>
                    </Item>
                  </Grid>

                  {/* Currently tracking / Suggestion Panel */}
                  <Grid item xs={1} md={3}>
                    <Item className="h-full py-4 flex items-center justify-end">
                      <ProfileNavButton></ProfileNavButton>
                    </Item>
                  </Grid>
                </Grid>
                {children}
              </Container>
              <BottomNavigation
                showLabels
                sx={{
                  flexDirection: { md: "column", xs: "row" },
                  height: { xs: "auto", md: "100%" },
                  paddingTop: { xs: "0px", md: "96px" },
                  justifyContent: { xs: "center", md: "start" },
                }}
              >
                {/* <BottomNavigationAction
                  label=""
                  icon={<MenuIcon />}
                  className="grow-0 p-3 mb-5 mt-3"
                  sx={{ display: { xs: "none", md: "block" } }}
                /> */}
                <BottomNavigationAction
                  label="Home"
                  icon={<Home />}
                  className="grow-0 p-3"
                  component={Link}
                  href={"/"}
                />
                <BottomNavigationAction
                  label="Schedule"
                  icon={<CalendarMonth />}
                  className="grow-0 p-3"
                  component={Link}
                  href={"/day"}
                />
              </BottomNavigation>
            </Box>
          </main>
        </ThemeRegistry>
      </body>
    </html>
  );
}
