import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Planner",
  description: "Generated by create next app",
};

import Box from "@mui/material/Box";
import TextField from "@mui/material/TextField";
import Container from "@mui/material/Container";
import Grid from "@mui/material/Grid";
import Item from "@mui/material/Grid";
import Typography from "@mui/material/Typography";
import BottomNavigation from "@mui/material/BottomNavigation";
import BottomNavigationAction from "@mui/material/BottomNavigationAction";

// icons
import RestoreIcon from "@mui/icons-material/Restore";
import FavoriteIcon from "@mui/icons-material/Favorite";
import LocationOnIcon from "@mui/icons-material/LocationOn";
import MenuIcon from "@mui/icons-material/Menu";

import ThemeRegistry from "../components/ThemeRegistry";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="dark" className="h-full">
      <body className="h-full">
        <ThemeRegistry options={{ key: "mui", prepend: false }}>
          <main className="h-full">
            <Box
              className="h-full flex"
              sx={{
                flexDirection: { xs: "column", md: "row-reverse" },
              }}
            >
              <Container maxWidth={false} className="grow">
                <Grid container spacing={2} className="h-28 w-full">
                  <Grid
                    item
                    xs={0}
                    md={3}
                    sx={{ display: { md: "block", xs: "none" } }}
                  >
                    <Item className="w-full h-full py-4 flex items-center">
                      <Typography variant="h4">Planner</Typography>
                    </Item>
                  </Grid>
                  <Grid item xs={12} md={6}>
                    <Item className="w-full h-full py-4 flex items-center">
                      <TextField
                        id="search"
                        variant="outlined"
                        className="w-full"
                        placeholder="Search"
                      />
                    </Item>
                  </Grid>
                </Grid>
                {children}
              </Container>
              <BottomNavigation
                showLabels
                sx={{
                  flexDirection: { md: "column", xs: "row" },
                  height: { xs: "auto", md: "100%" },
                  justifyContent: { xs: "center", md: "start" },
                }}
              >
                <BottomNavigationAction
                  label=""
                  icon={<MenuIcon />}
                  className="grow-0 p-3 mb-5 mt-3"
                  sx={{ display: { xs: "none", md: "block" } }}
                />
                <BottomNavigationAction
                  label="Recents"
                  icon={<RestoreIcon />}
                  className="grow-0 p-3"
                />
                <BottomNavigationAction
                  label="Favorites"
                  icon={<FavoriteIcon />}
                  className="grow-0 p-3"
                />
                <BottomNavigationAction
                  label="Nearby"
                  icon={<LocationOnIcon />}
                  className="grow-0 p-3"
                />
              </BottomNavigation>
            </Box>
          </main>
        </ThemeRegistry>
      </body>
    </html>
  );
}
