
### Create session CURL

curl -u 90b5dfbf377f4e532fe14c5e3bf49c7e:api_token -X POST https://api.track.toggl.com/api/v9/me/sessions

### Create session REST

POST https://api.track.toggl.com/api/v9/me/sessions
Authorization: Basic OTBiNWRmYmYzNzdmNGU1MzJmZTE0YzVlM2JmNDljN2U6YXBpX3Rva2Vu
Content-Type: application/json

{
  "remember_me": true
}

### Delete session REST

DELETE https://api.track.toggl.com/api/v9/me/sessions


### GET time entries

GET https://api.track.toggl.com/api/v9/me/time_entries
Content-Type: application/json